name: ImageBuilder
# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.7.3
        env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          url: https://hvp.akeyless.io
          # url: https://akeyless-gw:8200
          tlsSkipVerify: true
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/ci/Gitsecret/actions ci/Gitsecret/actions | action ;
      - name: Secret from Akeyless
        run: echo "${{ env.app_secret }}"
